### ISSUE TITLE
transformer version flax version

### ISSUE THREAD

**Issue by guanhdrmq** [gchhablani/multilingual-vqa#2]
Hi, when to use multiinglual-vqa model, transfomer=4.25.1 flax=0.75, it happes version mismatch. 
Can you share a few hints for this issue? many thanks

Traceback (most recent call last):
  File "D:\multimodal_robustness\clip_vision_bert.py", line 219, in <module>
    model = FlaxCLIPVisionBertForSequenceClassification.from_pretrained(
  File "D:\multimodal_robustness\multilingual_vqa\models\flax_clip_vision_bert\modeling_clip_vision_bert.py", line 991, in from_pretrained
    return super().from_pretrained(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\transformers\modeling_flax_utils.py", line 807, in from_pretrained
    model = cls(config, *model_args, _do_init=_do_init, **model_kwargs)
  File "D:\multimodal_robustness\multilingual_vqa\models\flax_clip_vision_bert\modeling_clip_vision_bert.py", line 857, in __init__
    module = self.module_class(config=config, dtype=dtype,  **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\flax\linen\kw_only_dataclasses.py", line 233, in init_wrapper
    dataclass_init(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument '_do_init'

**Comment by sanchit-gandhi** [comment]
To use the latest version of `transformers`, you need to add the modelling code changes outlined in this PR: https://github.com/huggingface/transformers/pull/16148/files#diff-ec6cda27c1cdc8063ecee13f97dab4acc7194cdbbf15c512bcc8f04a3f4a254d

Specifically, see the changes made to the `__init__` and `init_weights` method of `FlaxCLIPTextPreTrainedModel` in `modeling_flax_clip.py`. You should make sure that every `__init__` and `init_weights` method receives this update, adding the `_do_init` argument and also the new logic for `init_weights`.
